ln -s $HOME/Documents/mystuff/dotfiles/.i3/ 		$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.i3status.conf 	$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.bashrc 		$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.bash_aliases 	$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.bash_profile 	$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.vimrc 		$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.inputrc 	$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.Xresources 	$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.xprofile 	$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.Xdefaults 	$HOME/
ln -s $HOME/Documents/mystuff/dotfiles/.dircolors 	$HOME/
